version: '3.7'

services:
  web:
    build: .
    command: python /app/web_rz/rz_site/manage.py runserver 0.0.0.0.8000
    volumes:
      - .:/app/web_rz
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  volumes:
    postgres_data: