# Generated by Django 4.2 on 2023-04-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='topic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
