# Generated by Django 4.2 on 2023-04-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
